controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

cart_update:
    path: /cart/update/{id}
    controller: App\Controller\CartController::updateQte
    methods: POST
